### ISSUE TITLE
Hello, are you the developer of Tobii?

### ISSUE THREAD

**Issue by leeweizhe1993** [grebtsew/Tobii_Glasses_2_Python3_And_C#1]

**Comment by grebtsew** [comment]
No I am not, however I had the opportunity to try one of their products "Tobii Glasses 2" this summer. I needed access to data from the device in Python3. Therefore I created this repo where I assumed from Tobii Glasses api for python2. The original api code can be downloaded from here : https://www.tobiipro.com/product-listing/tobii-pro-glasses-2-sdk/#Download
